services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    restart: always
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=2048M
    volumes:
      - ./cassandra_storage:/var/lib/cassandra
    ports:
      - 7000:7000
      - 9042:9042
  cassandra-load-imagerec:
    container_name: cassandra-load-imagerec
    image: cassandra:latest
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=2048M
    depends_on:
      - cassandra
    volumes:
      - ./config/cqlshrc:/cqlshrc
      - ./ddl/imagerec.cql:/imagerec.cql:ro
      - ./imagerec_prod:/imagerec_prod:ro
      - ./ingestion_status:/ingestion_status:rw
    command: /bin/bash -c "sleep 60 && cqlsh cassandra --cqlshrc /cqlshrc -f /imagerec.cql"
  sqlite:
    container_name: sqlite
    build:
      context: .
      dockerfile: Dockerfile.sqlite
    volumes:
      - ./imagerec_prod:/imagerec_prod:rw
      - ./ddl/imagerec.sqlite:/imagerec.sqlite:ro
